{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let content=$class_attribute.content}
{* Selection method. *}
<div class="block">
    <label>{'Selection method'|i18n( 'design/standard/class/datatype' )}:</label>
    <p>{$content.selection_type|choose( 'Browse'|i18n( 'design/standard/class/datatype' ), 'Drop-down list'|i18n( 'design/standard/class/datatype' ), 'Drop-down tree'|i18n( 'design/standard/class/datatype' ) )}</p>
</div>
{/let}


