{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $my_node=fetch( 'content', 'node', hash( 'node_id', $attribute.data_int ) )}
{if $my_node.hidden_status_string|contains('Sichtbar')}
   {node_view_gui view=text_linked content_node=$my_node}
{else}
   {'No relation'|i18n( 'design/standard/content/datatype' )}
{/if}